language: objective-c  
os: osx  
osx_image: xcode7
before_install:  
- export LANG=en_US.UTF-8
- npm install -g npm@2.14.5
script:  
- npm install
- ionic platform add ios
- ionic build ios --device --release
- ionic build ios --device --release
